### ISSUE TITLE
[Bug]: CUDA ERROR

### ISSUE THREAD

**Issue by No565** [continue-revolution/sd-webui-animatediff#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I got this error after trying to generate something :

RuntimeError: CUDA error: invalid configuration argument CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

AnimateDiff worked well previously, than i installed some other extensions which altered apparently some things.. I did not know before that i could install everything in a separate environment.. I have a list of the installed versions, but i have no list of my "before versions".

Could you specify all the dependencies so i could look after the error with the "git list" option, please ? Like Numpy version xy .. and so on. Or is there a more simple way to resolve this issue ?
I don´t exactly know where to put the "CUDA_LAUNCH_BLOCKING=1" and the "TORCH_USE_CUDA_DSA" to be honest :/ 

Thank you in advance !!!

### Steps to reproduce the problem

1. write a prompt
2. execute
3. error

### What should have happened?

A moving gif file ( : 

### Commit where the problem happens

webui:  probably here, i got that message under the output window, where all the error messages are written in the webui. ( same place for the png info normally )
extension: 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
2023-09-19 12:30:42,248 - AnimateDiff - INFO - AnimateDiff process start.████████████████| 5/5 [00:07<00:00,  1.41s/it]
2023-09-19 12:30:42,249 - AnimateDiff - INFO - You are using mm_sd_v15_v2.ckpt, which has been tested and supported.
2023-09-19 12:30:42,250 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
2023-09-19 12:30:46,909 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-09-19 12:30:47,406 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2023-09-19 12:30:47,407 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2023-09-19 12:30:47,408 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2023-09-19 12:30:47,408 - AnimateDiff - INFO - Setting DDIM alpha.
2023-09-19 12:30:47,410 - AnimateDiff - INFO - Injection finished.
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(xhx98p0mcu75a87)', 'cat in a hat waving', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000279C27FE530>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x00000279A90EA1A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000279A90E8E20>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000279A90E91B0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000279C2800A00>, None, False, '0', 'C:\\Users\\No565\\Documents\\Stable Diffusion - Automatic1111\\stable-diffusion-webui\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 26, in mm_tes_forward
        x = layer(x, context)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 86, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 150, in forward
        hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, video_length=video_length)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 212, in forward
        hidden_states = attention_block(
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 559, in forward
        hidden_states = self._memory_efficient_attention(query, key, value, attention_mask, sd_hijack.current_optimizer.name)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 467, in _memory_efficient_attention
        hidden_states = xformers.ops.memory_efficient_attention(
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 310, in _memory_efficient_attention_forward
        out, *_ = op.apply(inp, needs_gradient=False)
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
        out, lse, rng_seed, rng_offset = cls.OPERATOR(
      File "C:\Users\No565\Documents\Stable Diffusion - Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 502, in __call__
        return self._op(*args, **kwargs or {})
    RuntimeError: CUDA error: invalid configuration argument
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


---
```

### Console logs

```Shell
There are no logs, its emptly . "Element not found" 
I opend SD and i started to write the prompt for Animatediff, i did not created other imgs.
```

**Comment by continue-revolution** [comment]
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.11.4  •  torch: 2.0.1+cu117  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [7f96a1a9ca](https://google.com/search?q=7f96a1a9ca9b3a3242a9ae95d19284f0d2da8d5282b42d2d974398bf7663a252)

**Comment by continue-revolution** [comment]
Another possibility is your hardward. I previously used 3090 and it raised the same error. Now I upgrade to 4090 and problem disappeared.

**Comment by continue-revolution** [comment]
0.0.21 will cause trouble. Use 0.0.20 for now. I will work with some other devs on finding this problem.

**Comment by continue-revolution** [comment]
https://github.com/facebookresearch/xformers/issues/845

**Comment by GuruVirus** [comment]
I'm getting the same with:
version: [1.6.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2
No other extensions.
RTX4090, during the process VRAM idles around 8.6GB.

**Comment by continue-revolution** [comment]
Use sdp instead of xformers for now. It is the problem of xformers.

**Comment by No565** [comment]
Thank you for the quick reply! I waited for the next update to see maybe it will fix it but not, its the same ( : ... 

I have :

version: [v1.6.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.44.3  •  numpy: 1.24.2 •Tenserflov: 2.13.0 

The python version and the torch are not the same, maybe thats the problem ? I think i had the same python version before as well , so than torch o gradio ? .. I remember that the numpy version was changed as well, for this reason i included, nut sure if this have something to do with it .. 

You said "For now you can use sdp (use —opt-sdp-attention for command line args, instead of —xformers)."  where exactly should i put it ? In which folder shuld i look for which file ? 

Thx :)

**Comment by continue-revolution** [comment]
@No565 you have 2 options:
1. Go to Settings/AnimateDiff and you’ll know what you should change. Don’t forget to click “Apply Settings”
2. Change your command line arguments, exactly where you enable xformers. Replace --xformers and with --opt-sdp-attention

**Comment by paboum** [comment]
https://learnpython.com/blog/python-requirements-file/

**Comment by No565** [comment]
@continue-revolutio You are a Genius! The first option worked ! Although its way slower as it was before with xformers.
 Thanks, i learned 2 new things! :)

**Comment by continue-revolution** [comment]
I recommend choosing the second option in settings (use sdp when you enable xformers). From my own testing, it has exactly the same effect as xformers in terms of VEAM optimizations.
