### ISSUE TITLE
[Bug]: Animatediff giving error when adetailer is enabled

### ISSUE THREAD

**Issue by xerun** [continue-revolution/sd-webui-animatediff#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

When I enable Adetailer and run animateDiff after it finish generating the fames when it try to use Adetailer to fix the face the below error is shown and the entire webui is not functional anymore. I need to restart the application to make it work again.

### Steps to reproduce the problem

1. Enable adetailer
2. Enable animatediff
3. Generate

### What should have happened?

I should have generated the animation with face fixed.

### Commit where the problem happens

•  webui: v1.8.0  
•  python: 3.10.6  
•  torch: 2.1.2+cu121  
•  xformers: 0.0.23.post1  
•  gradio: 3.41.2  
•  checkpoint: 7c819b6d13

### Command Line Arguments

```Shell
--xformers --api --theme=dark
```

### Console logs

```Shell
0: 640x384 1 face, 60.0ms
Speed: 1.5ms preprocess, 60.0ms inference, 13.0ms postprocess per image at shape (1, 3, 640, 384)
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]2024-03-04 19:28:25,502 - AnimateDiff - INFO - inner model forward hooked
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [102,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [103,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [104,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [105,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [106,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [107,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [108,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [109,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [110,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [111,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [112,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [113,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [114,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [115,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [116,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [117,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [118,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [119,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [120,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [121,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [122,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [265,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [32,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [34,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [35,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [36,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [37,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [38,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [39,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [40,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [42,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [43,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [44,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [45,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [46,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [47,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [48,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [49,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [50,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [51,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [52,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [53,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [54,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [55,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [56,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [57,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [58,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [59,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [60,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [61,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [62,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [246,0,0], thread: [63,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
Exception in thread MemMon:
Traceback (most recent call last):
  File "C:\Users\prith\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  0%|                                                                                            | 0/5 [00:01<?, ?it/s]
    self.run()
  File "E:\AI_Apps\stable-diffusion-webui\modules\memmon.py", line 53, in run
    free, total = self.cuda_mem_get_info()
  File "E:\AI_Apps\stable-diffusion-webui\modules\memmon.py", line 34, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 663, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

*** Error running postprocess_image: E:\AI_Apps\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "E:\AI_Apps\stable-diffusion-webui\modules\scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\AI_Apps\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    RuntimeError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22631-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.8.0                                                                                         │ │
    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5                                                       │ │
    │ │ Commandline │ ['launch.py', '--xformers', '--api', '--theme=dark']                                           │ │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.1.20', 'mediapipe':  │ │
    │ │             │ '0.10.10'}                                                                                     │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                               Inputs                                                                             │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                              │
    │ ┃                 ┃ Value                                         ┃                                              │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                              │
    │ │          prompt │ girl                                          │                                              │
    │ │ negative_prompt │                                               │                                              │
    │ │          n_iter │ 1                                             │                                              │
    │ │      batch_size │ 16                                            │                                              │
    │ │           width │ 432                                           │                                              │
    │ │          height │ 768                                           │                                              │
    │ │    sampler_name │ DPM++ 2M Karras                               │                                              │
    │ │       enable_hr │ False                                         │                                              │
    │ │     hr_upscaler │ 4x-UltraSharp                                 │                                              │
    │ │      checkpoint │ majicmixRealistic_v7.safetensors [7c819b6d13] │                                              │
    │ │             vae │ Automatic                                     │                                              │
    │ │            unet │ Automatic                                     │                                              │
    │ └─────────────────┴───────────────────────────────────────────────┘                                              │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 24.3.0          │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ E:\AI_Apps\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper     │             │
    │ │                                                                                                  │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:778 in              │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │    777 │   │   │   │   │   continue                                                              │             │
    │ │ ❱  778 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
    │ │    779                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:739 in              │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │    738 │   │   │   try:                                                                          │             │
    │ │ ❱  739 │   │   │   │   processed = process_images(p2)                                            │             │
    │ │    740 │   │   │   except NansException as e:                                                    │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\processing.py:785 in process_images                    │             │
    │ │                                                                                                  │             │
    │ │    784 │   │                                                                                     │             │
    │ │ ❱  785 │   │   res = process_images_inner(p)                                                     │             │
    │ │    786                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\processing.py:921 in process_images_inner              │             │
    │ │                                                                                                  │             │
    │ │    920 │   │   │   with devices.without_autocast() if devices.unet_needs_upcast else devices.au  │             │
    │ │ ❱  921 │   │   │   │   samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.u  │             │
    │ │    922                                                                                           │             │
    │ │                                                                                                  │             │
    │ �� E:\AI_Apps\stable-diffusion-webui\modules\processing.py:1661 in sample                           │
│
    │ │                                                                                                  │             │
    │ │   1660 │   │                                                                                     │             │
    │ │ ❱ 1661 │   │   samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, u  │             │
    │ │   1662                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py:188 in sample_img2img        │             │
    │ │                                                                                                  │             │
    │ │   187 │   │                                                                                      │             │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │             │
    │ │   189                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\sd_samplers_common.py:261 in launch_sampling           │             │
    │ │                                                                                                  │             │
    │ │   260 │   │   try:                                                                               │             │
    │ │ ❱ 261 │   │   │   return func()                                                                  │             │
    │ │   262 │   │   except RecursionError:                                                             │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py:188 in <lambda>              │             │
    │ │                                                                                                  │             │
    │ │   187 │   │                                                                                      │             │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │             │
    │ │   189                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py:115 in       │             │
    │ │ decorate_context                                                                                 │             │
    │ │                                                                                                  │             │
    │ │   114 │   │   with ctx_factory():                                                                │             │
    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   116                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py:594 in        │             │
    │ │ sample_dpmpp_2m                                                                                  │             │
    │ │                                                                                                  │             │
    │ │   593 │   for i in trange(len(sigmas) - 1, disable=disable):                                     │             │
    │ │ ❱ 594 │   │   denoised = model(x, sigmas[i] * s_in, **extra_args)                                │             │
    │ │   595 │   │   if callback is not None:                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py:1518 in      │             │
    │ │ _wrapped_call_impl                                                                               │             │
    │ │                                                                                                  │             │
    │ │   1517 │   │   else:                                                                             │             │
    │ │ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │             │
    │ │   1519                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py:1527 in      │             │
    │ │ _call_impl                                                                                       │             │
    │ │                                                                                                  │             │
    │ │   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │
    │ │ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │             │
    │ │   1528                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py:237 in forward             │             │
    │ │                                                                                                  │             │
    │ │   236 │   │   │   if shared.opts.batch_cond_uncond:                                              │             │
    │ │ ❱ 237 │   │   │   │   x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_i   │             │
    │ │   238 │   │   │   else:                                                                          │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py:1518 in      │             │
    │ │ _wrapped_call_impl                                                                               │             │
    │ │                                                                                                  │             │
    │ │   1517 │   │   else:                                                                             │             │
    │ │ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │             │
    │ │   1519                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py:1527 in      │             │
    │ │ _call_impl                                                                                       │             │
    │ │                                                                                                  │             │
    │ │   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │
    │ │ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │             │
    │ │   1528                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\AI_Apps\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py: │             │
    │ │ 152 in mm_sd_forward                                                                             │             │
    │ │                                                                                                  │             │
    │ │   151 │   │   │   │   │   out = self.original_forward(                                           │             │
    │ │ ❱ 152 │   │   │   │   │   │   x_in[_context], sigma_in[_context],                                │             │
    │ │   153 │   │   │   │   │   │   cond={k: ([v[0][_context]] if isinstance(v, list) else v[_contex   │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ RuntimeError: CUDA error: device-side assert triggered                                                           │
    │ CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be     │
    │ incorrect.                                                                                                       │
    │ For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                           │
    │ Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                              │
    │                                                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

---
*** Error completing request
*** Arguments: ('task(h0iw4vqi8zx6br2)', <gradio.routes.Request object at 0x000001D7D40E18A0>, 'girl', '', ['emb_negative'], 12, 'DPM++ 2M Karras', 1, 1, 5, 768, 432, False, 0.55, 2, '4x-UltraSharp', 5, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 432, 'ad_inpaint_height': 768, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001D7D4231720>, UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), None, False, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, False, False, 0.5, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "E:\AI_Apps\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\AI_Apps\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\AI_Apps\stable-diffusion-webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "E:\AI_Apps\stable-diffusion-webui\modules\processing.py", line 785, in process_images
        res = process_images_inner(p)
      File "E:\AI_Apps\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 48, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\AI_Apps\stable-diffusion-webui\modules\processing.py", line 1041, in process_images_inner
        devices.torch_gc()
      File "E:\AI_Apps\stable-diffusion-webui\modules\devices.py", line 81, in torch_gc
        torch.cuda.empty_cache()
      File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 159, in empty_cache
        torch._C._cuda_emptyCache()
    RuntimeError: CUDA error: device-side assert triggered
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


---
Traceback (most recent call last):
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI_Apps\stable-diffusion-webui\modules\call_queue.py", line 77, in f
    devices.torch_gc()
  File "E:\AI_Apps\stable-diffusion-webui\modules\devices.py", line 81, in torch_gc
    torch.cuda.empty_cache()
  File "E:\AI_Apps\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 159, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by wildwindfeng** [comment]
Same issue here. After upgrade animateDiff today with Webui1.8
Old version was working fine

**Comment by continue-revolution** [comment]
someone please paste a screenshot of your adetailer. setup I don't know how to use it and I don't use it.

**Comment by xerun** [comment]
Hello, below is the setup, you just need to enable the adetailer, nothing else need to be changed in adetailer.

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/26061074/eaecb9e1-890f-448d-abdb-a2bc6e89fbd0)

**Comment by Sarimae** [comment]
Same Issue here

**Comment by zetteron** [comment]
same issue

**Comment by turugi-ni** [comment]
I have the same problem.In addition, it generates images larger than 512 x 512.Use multiple Lora.Use upscaler extensions such as latent-upscale. multidiffusion-upscaler.Enter a large number in Number of frames. Probably more than 10 seconds.The error content varies, but finally it becomes RuntimeError: CUDA error: device-side assert triggered.My graphics board is nvida rtx 4060ti vram 16GB, so the image generation speed is slow, but I think I have enough vram.

**Comment by gregreardon** [comment]
same issue, even after todays update.
How to replicate.
1. Enable Adetailer
2.Enable Animatediff
When generating after animatediff process ends and adetailer starts errors below happen

2024-03-07 20:47:05,755 - AnimateDiff - INFO - Saving output formats: MP4
2024-03-07 20:47:05,755 - AnimateDiff - INFO - AnimateDiff process end.

0: 640x448 1 face, 1425.0ms
Speed: 14.7ms preprocess, 1425.0ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 448)
  0%|                                                     | 0/9 [00:00<?, ?it/s]2024-03-07 20:47:10,476 - AnimateDiff - INFO - inner model forward hooked
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [64,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [65,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [66,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [67,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [68,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [69,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [70,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [71,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [72,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [73,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [74,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [75,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [76,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [77,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [78,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [79,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [80,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [81,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [82,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [83,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [84,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [85,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [86,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [87,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [88,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [89,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [90,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [91,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [92,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [93,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [94,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [116,0,0], thread: [95,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [99,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [100,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [101,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [102,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [103,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [104,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [105,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [106,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [107,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [108,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [109,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [110,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [111,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [112,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [113,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [114,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [115,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [116,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [117,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [118,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [119,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [120,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [121,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [122,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [176,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
  0%|                                                     | 0/9 [00:00<?, ?it/s]
Exception in thread MemMon:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/memmon.py", line 53, in run
    free, total = self.cuda_mem_get_info()
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/memmon.py", line 34, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py", line 655, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

*** Error running postprocess_image: /storage/stable-diffusion/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/adetailer/adetailer/traceback.py", line 159, in wrapper
        raise error from None
    RuntimeError: 
    ╭──────────────────────────────────────────────────────────────────────────╮
    │                               System info                                │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                  ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Linux-5.19.0-45-generic-x86_64-with-glibc2.31          │ │
    │ │      Python │ 3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0]      │ │
    │ │     Version │ v1.8.0                                                 │ │
    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5               │ │
    │ │ Commandline │ ['webui.py', '--xformers', '--medvram',                │ │
    │ │             │ '--disable-safe-unpickle', '--share', '--gradio-auth', │ │
    │ │             │ 'me:me', '--enable-insecure-extension-access']         │ │
    │ │   Libraries │ {'torch': '2.2.0', 'torchvision': '0.17.0',            │ │
    │ │             │ 'ultralytics': '8.1.24', 'mediapipe': '0.10.11'}       │ │
    │ └─────────────┴────────────────────────────────────────────────────────┘ │
    │                                  Inputs                                  │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                              ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ photo of beautiful (DAG_Jade), woman with perfect  │ │
    │ │                 │ hair, (tennis court with net:1.3), (extremely      │ │
    │ │                 │ detailed CG unity 8k wallpaper), covered_nipples,  │ │
    │ │                 │ no_bra, professional majestic photography, (Leica  │ │
    │ │                 │ M6 Camera), 24mm, exposure blend, hdr, faded,      │ │
    │ │                 │ extremely intricate, High (Detail:1.1), Sharp      │ │
    │ │                 │ focus, dramatic, soft cinematic light, (looking at │ │
    │ │                 │ viewer), (detailed pupils), 4k textures, elegant,  │ │
    │ │                 │ ((cinematic look)), soothing tones, insane         │ │
    │ │                 │ details, hyperdetailed, low contrast, (epicPhoto), │ │
    │ │                 │ <lora:no_bra_v20:0.5> , (white tennis outfit:1.2), │ │
    │ │                 │ (seductive), (posing:1.5), (spreading legs:1.4)    │ │
    │ │ negative_prompt │ picPhoto-neg, (cleft), plastic, canvas frame,      │ │
    │ │                 │ cartoon, 3d, ((disfigured)), ((bad art)),          │ │
    │ │                 │ ((deformed)),((extra limbs)),((close up)),((b&w)), │ │
    │ │                 │ blurry, (((duplicate))), ((morbid)),               │ │
    │ │                 │ ((mutilated)), , extra fingers, mutated hands,     │ │
    │ │                 │ ((poorly drawn hands)), ((poorly drawn face)),     │ │
    │ │                 │ (((mutation))), (((deformed))), ((ugly)), blurry,  │ │
    │ │                 │ ((bad anatomy)), (((bad proportions))), ((extra    │ │
    │ │                 │ limbs)), cloned face, (((disfigured))), (out of    │ │
    │ │                 │ frame), ugly, extra limbs, (bad anatomy), gross    │ │
    │ │                 │ proportions, (malformed limbs), ((missing arms)),  │ │
    │ │                 │ ((missing legs)), (((extra arms))), (((extra       │ │
    │ │                 │ legs))), mutated hands, (fused fingers), (too many │ │
    │ │                 │ fingers), (((long neck))), Photoshop, video game,  │ │
    │ │                 │ ugly, tiling, poorly drawn hands, poorly drawn     │ │
    │ │                 │ feet, poorly drawn face, out of frame, mutation,   │ │
    │ │                 │ mutated, extra limbs, extra legs, extra arms,      │ │
    │ │                 │ disfigured, deformed, cross-eye, body out of       │ │
    │ │                 │ frame, blurry, bad art, bad anatomy, 3d render,    │ │
    │ │                 │ (tiara), (bad-hands-5), (boobs:1.6), ((bangs)),    │ │
    │ │                 │ (watermark, logo, text, lettering), (((tattoo))),  │ │
    │ │                 │ (((tattoos))), watermark, logo                     │ │
    │ │          n_iter │ 1                                                  │ │
    │ │      batch_size │ 16                                                 │ │
    │ │           width │ 512                                                │ │
    │ │          height │ 768                                                │ │
    │ │    sampler_name │ DPM++ 2M Karras                                    │ │
    │ │       enable_hr │ False                                              │ │
    │ │     hr_upscaler │ Latent                                             │ │
    │ │      checkpoint │ theTrualityEngine_trualityENGINEPRO.safetensors    │ │
    │ │             vae │ Automatic                                          │ │
    │ │            unet │ Automatic                                          │ │
    │ └─────────────────┴────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                │
    │ ┃                     ┃ Value           ┃                                │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                │
    │ │             version │ 24.3.0          │                                │
    │ │            ad_model │ face_yolov8n.pt │                                │
    │ │           ad_prompt │                 │                                │
    │ │  ad_negative_prompt │                 │                                │
    │ │ ad_controlnet_model │ None            │                                │
    │ │              is_api │ False           │                                │
    │ └─────────────────────┴─────────────────┘                                │
    │ ╭───────────────── Traceback (most recent call last) ──────────────────╮ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/extensions/adetaile │ │
    │ │ r/adetailer/traceback.py:139 in wrapper                              │ │
    │ │                                                                      │ │
    │ │   138 │   │   try:                                                   │ │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                       │ │
    │ │   140 │   │   except Exception as e:                                 │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/extensions/adetaile │ │
    │ │ r/scripts/!adetailer.py:778 in postprocess_image                     │ │
    │ │                                                                      │ │
    │ │    777 │   │   │   │   │   continue                                  │ │
    │ │ ❱  778 │   │   │   │   is_processed |= self._postprocess_image_inner │ │
    │ │    779                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/extensions/adetaile │ │
    │ │ r/scripts/!adetailer.py:739 in _postprocess_image_inner              │ │
    │ │                                                                      │ │
    │ │    738 │   │   │   try:                                              │ │
    │ │ ❱  739 │   │   │   │   processed = process_images(p2)                │ │
    │ │    740 │   │   │   except NansException as e:                        │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/processing. │ │
    │ │ py:785 in process_images                                             │ │
    │ │                                                                      │ │
    │ │    784 │   │                                                         │ │
    │ │ ❱  785 │   │   res = process_images_inner(p)                         │ │
    │ │    786                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/processing. │ │
    │ │ py:921 in process_images_inner                                       │ │
    │ │                                                                      │ │
    │ │    920 │   │   │   with devices.without_autocast() if devices.unet_n │ │
    │ │ ❱  921 │   │   │   │   samples_ddim = p.sample(conditioning=p.c, unc │ │
    │ │    922                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/processing. │ │
    │ │ py:1661 in sample                                                    │ │
    │ │                                                                      │ │
    │ │   1660 │   │                                                         │ │
    │ │ ❱ 1661 │   │   samples = self.sampler.sample_img2img(self, self.init │ │
    │ │   1662                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers │ │
    │ │ _kdiffusion.py:188 in sample_img2img                                 │ │
    │ │                                                                      │ │
    │ │   187 │   │                                                          │ │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self │ │
    │ │   189                                                                │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers │ │
    │ │ _common.py:261 in launch_sampling                                    │ │
    │ │                                                                      │ │
    │ │   260 │   │   try:                                                   │ │
    │ │ ❱ 261 │   │   │   return func()                                      │ │
    │ │   262 │   │   except RecursionError:                                 │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers │ │
    │ │ _kdiffusion.py:188 in <lambda>                                       │ │
    │ │                                                                      │ │
    │ │   187 │   │                                                          │ │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self │ │
    │ │   189                                                                │ │
    │ │                                                                      │ │
    │ │ /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:1 │ │
    │ │ 15 in decorate_context                                               │ │
    │ │                                                                      │ │
    │ │   114 │   │   with ctx_factory():                                    │ │
    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                       │ │
    │ │   116                                                                │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/repositories/k-diff │ │
    │ │ usion/k_diffusion/sampling.py:594 in sample_dpmpp_2m                 │ │
    │ │                                                                      │ │
    │ │   593 │   for i in trange(len(sigmas) - 1, disable=disable):         │ │
    │ │ ❱ 594 │   │   denoised = model(x, sigmas[i] * s_in, **extra_args)    │ │
    │ │   595 │   │   if callback is not None:                               │ │
    │ │                                                                      │ │
    │ │ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1 │ │
    │ │ 511 in _wrapped_call_impl                                            │ │
    │ │                                                                      │ │
    │ │   1510 │   │   else:                                                 │ │
    │ │ ❱ 1511 │   │   │   return self._call_impl(*args, **kwargs)           │ │
    │ │   1512                                                               │ │
    │ │                                                                      │ │
    │ │ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1 │ │
    │ │ 520 in _call_impl                                                    │ │
    │ │                                                                      │ │
    │ │   1519 │   │   │   │   or _global_forward_hooks or _global_forward_p │ │
    │ │ ❱ 1520 │   │   │   return forward_call(*args, **kwargs)              │ │
    │ │   1521                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers │ │
    │ │ _cfg_denoiser.py:237 in forward                                      │ │
    │ │                                                                      │ │
    │ │   236 │   │   │   if shared.opts.batch_cond_uncond:                  │ │
    │ │ ❱ 237 │   │   │   │   x_out = self.inner_model(x_in, sigma_in, cond= │ │
    │ │   238 │   │   │   else:                                              │ │
    │ │                                                                      │ │
    │ │ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1 │ │
    │ │ 511 in _wrapped_call_impl                                            │ │
    │ │                                                                      │ │
    │ │   1510 │   │   else:                                                 │ │
    │ │ ❱ 1511 │   │   │   return self._call_impl(*args, **kwargs)           │ │
    │ │   1512                                                               │ │
    │ │                                                                      │ │
    │ │ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1 │ │
    │ │ 520 in _call_impl                                                    │ │
    │ │                                                                      │ │
    │ │   1519 │   │   │   │   or _global_forward_hooks or _global_forward_p │ │
    │ │ ❱ 1520 │   │   │   return forward_call(*args, **kwargs)              │ │
    │ │   1521                                                               │ │
    │ │                                                                      │ │
    │ │ /storage/stable-diffusion/stable-diffusion-webui/extensions/sd-webui │ │
    │ │ -animatediff/scripts/animatediff_infv2v.py:152 in mm_sd_forward      │ │
    │ │                                                                      │ │
    │ │   151 │   │   │   │   │   out = self.original_forward(               │ │
    │ │ ❱ 152 │   │   │   │   │   │   x_in[_context], sigma_in[_context],    │ │
    │ │   153 │   │   │   │   │   │   cond={k: ([v[0][_context]] if isinstan │ │
    │ ╰──────────────────────────────────────────────────────────────────────╯ │
    │ RuntimeError: CUDA error: device-side assert triggered                   │
    │ CUDA kernel errors might be asynchronously reported at some other API    │
    │ call, so the stacktrace below might be incorrect.                        │
    │ For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                   │
    │ Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.      │
    │                                                                          │
    ╰──────────────────────────────────────────────────────────────────────────╯

**Comment by favortel** [comment]
same issue

**Comment by amida168** [comment]
I have the same problem. After struggling to get it to work again, I ended up using ReActor to swap the face. I found that it's actually working better with ReActor. The face is more consistent now.

**Comment by continue-revolution** [comment]
I have reproduced this problem on my end. There are at least 2 problems with adetailer -
1. when prompt travel is applied, it throws an "index out of bound" error. It seems that this is because adetailer process images sequentially and my code cannot successfully do prompt interpolation.
2. when prompt travel is NOT applied, it throws CUDA error. It seems that this is because adetailer assume that it is fixing one image but my code assume that it is generating 16 frames.

It seems that adetailer might not be a good fit even if I find some way to resolve this issue, because adetailer process images sequentially one-by-one, which means that AnimateDiff can only see 1 image at a time, and the output must have no consistency at all. Even if I manage to find some way to fix it (which I will), I would not expect the performance to be satisfactory at all.

I would like to collect some feedback from you guys while I am trying to fix it, or find an alternative such as refactoring my segment anything extension.
1. why do you want to use adetailer? is it for face detail improvement, or something else?
2. if you have _successfully_ applied adetailer with AnimateDiff before (here "successfully" means that there is no error on the terminal, but the performance could be anything between perfect and shit), have you ever get any temporal consistent results? You can send me some examples here if you have.

**Comment by xerun** [comment]
Yes mainly for face detail.

Below is an example without adetailer created on March 15, 2024
![00000-382719304](https://github.com/continue-revolution/sd-webui-animatediff/assets/26061074/a601f58c-bcb1-46be-bc37-8a76bf4c3fdc)

Below is an example with adetailer created on Feb 18, 2024 (before it broke)
![ezgif-6-5e6776f523](https://github.com/continue-revolution/sd-webui-animatediff/assets/26061074/ebebaa0c-b147-4e85-a6f2-3427a5cb9539)

**Comment by continue-revolution** [comment]
@xerun good thing: seems that adetailer did preserve temporal consistency; bad thing: there seems to be no difference at all between your 2 examples

**Comment by wildwindfeng** [comment]
> @xerun good thing: seems that adetailer did preserve temporal consistency; bad thing: there seems to be no difference at all between your 2 examples

Actually there will be the huge difference when face is small in the picture. Smaller faces tend to be distorted before adetailer, after apply adetailer, face will be far more better

**Comment by amida168** [comment]
I used it to swap face and detail improvement. By default, the consistency is bad. I had to decrease the denoising strength to get better consistency.

I tried to insert my file, but it's too big.

**Comment by continue-revolution** [comment]
I have fixed the adetailer issue. There will be a bunch of warning on your terminal. If you believe that using adetailer is a good practice, please ignore those warnings.

**Comment by amida168** [comment]
Yes, it's working again. Thank you!

**Comment by moonsunstars39** [comment]
Is that possible to hijack the Adetailer process in order to add the motion module into Adetailer's checkpoint ?
