### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dnozz** [continue-revolution/sd-webui-animatediff#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

RuntimeError: CUDA error: device-side assert triggered  (solution in #174 didn't fix)

Python == 3.10.6
cuda == 12.1 ?
torch==2.1.2
torchvision==0.16.2
RTX 3070

SD was close to the maserpiece I was trying to produce, so I didn't even change any settings, just simply ran the same setup again and error'd out. Even after restarting the console it still immediately errors. Restart PC, same. I removed xformers from my webui-user.bat file tried a few other default optimizations from the dropdown. It ran once on "auto" optimization, the second time broke it. Trying to delete "venv" and reinstalling those guys from cache didn't work either..

Console:
https://pastebin.com/esxbDVcE

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
N/A     The same settings that threw the error worked just before the error. Nothing was changed in the WebUI.

### What should have happened?

compile a video 😏

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --no-half-vae --disable-nan-check --xformers    &
set COMMANDLINE_ARGS= --no-half-vae --disable-nan-check

Error originally with --xformers. I found "RuntimeError: CUDA error: device-side assert triggered #174" 
which seemed the issue was due to xformers. I removed it from the webui-users.bat file, reset the console, 
but that didn't seem to help.
```

### Console logs

```Shell
https://pastebin.com/esxbDVcE
```

**Comment by continue-revolution** [comment]
screenshot everything in your ui here. most likely you are using adetailer, if so, please update everything.

**Comment by Serpens66** [comment]
Not sure if it is the same cause, but I also get this "index out of bounds" error message in console as soon the negative prompts go above the 75-character limit (although tutorial states that negative prompts would have a higher limit and the problem from this would be sth else). After this happens a restart is required.

Using less characters or also enabling the Optimization Setting
"Pad prompt/negative prompt 
(improves performance when prompt and negative prompt have different lengths; changes seeds)"
solves it (issue does not happen then).

**Comment by continue-revolution** [comment]
@Serpens66  Holy shit this might be the real cause some people fucked things up. Thanks for bringing this to my attention.

**Comment by SuouK** [comment]
> Chết tiệt, đây có thể là nguyên nhân thực sự khiến một số người đụ mọi thứ. Cảm ơn bạn đã mang điều này đến sự chú ý của tôi.

I got the same error and tried writing less than 75 words and it worked. but there is a problem that too few words are used which greatly limits it.

**Comment by espritdautomne** [comment]
i just used a 4 words sentence and did it anyway. Waiting for a viable alternative to that garbage.
